### ISSUE TITLE
01 -- Love Your Grammar -- Heidi Roude

### ISSUE THREAD

**Issue by HRoude** [TheIronYard--Orlando/2015--SUMMER--ROR#12]
- [X] **Yak Shaving**
  - [X] Create WIP Issue: `01 -- Love Your Grammar`
  - [X] Create WIP Branch: `USERNAME.github.io:01--love-your-grammar`
    - [X] Add `README.md`
    - [X] Open Pull Request to `USERNAME.github.io:master`
  - [X] Add link to PR in `USERNAME.github.io` to _WIP Issue_
- [X] **Reading About Ruby**
  - [X] Start the Ruby Primer at [Ruby Monk](https://rubymonk.com/learning/books/1-ruby-primer). Complete the following sections:
    - [X] Introduction to Ruby Objects
    - [X] Introduction to Strings
    - [X] Arrays in Ruby
    - [x] Hashes in Ruby
- [x] **Writing About Ruby**
  - [x] Create `about/ruby.md` in `USERNAME.github.io:01--love-your-grammar`
  - [x] Explain basic classes: Numeric, String, Array, Hash
- [x] **GitHubbing to Know You**
  - [x] Fork `TheIronYard--Orlando/student-roster`
  - [x] Duplicate `TEMPLATE.md` as `USERNAME.md` using your Github username
  - [x] Fill in your name and avatar _only_
  - [x] Open a Pull Request from your fork to the original
  - [x] Add a link to the PR to your _WIP Issue_
- [x] **HTML**
  - [x] Create `index.html` in your `TIY-Assignments` repo 
  - [x] That file should have HTML5 doctype, a head tag, title tag, body tag, and some text.

**Comment by HRoude** [comment]
https://github.com/HRoude/HRoude.github.io/pull/1

**Comment by HRoude** [comment]
https://github.com/TheIronYard--Orlando/student-roster/pull/31

**Comment by bgates** [comment]
@HRoude good job! I left some comments on https://github.com/HRoude/HRoude.github.io/pull/1.
Also, please leave the issues open; I'll close them myself. Thanks!
