### ISSUE TITLE
01 -- Love Your Grammar -- JOHN BIER

### ISSUE THREAD

**Issue by johnmbier** [TheIronYard--Orlando/2015--SUMMER--ROR#13]
- [x] **Yak Shaving**
  - [x] Create WIP Issue: `01 -- Love Your Grammar`
  - [x] Create WIP Branch: `USERNAME.github.io:01--love-your-grammar`
    - [x] Add `README.md`
    - [x] Open Pull Request to `USERNAME.github.io:master`
  - [x] Add link to PR in `USERNAME.github.io` to _WIP Issue_
- [x] **Reading About Ruby**
  - [x] Start the Ruby Primer at [Ruby Monk](https://rubymonk.com/learning/books/1-ruby-primer). Complete the following sections:
    - [x] Introduction to Ruby Objects
    - [x] Introduction to Strings
    - [x] Arrays in Ruby
    - [x] Hashes in Ruby
- [x] **Writing About Ruby**
  - [x] Create `about/ruby.md` in `USERNAME.github.io:01--love-your-grammar`
  - [ ] Explain basic classes: Numeric, String, Array, Hash
- [x] **GitHubbing to Know You**
  - [x] Fork `TheIronYard--Orlando/student-roster`
  - [x] Duplicate `TEMPLATE.md` as `USERNAME.md` using your Github username
  - [x] Fill in your name and avatar _only_
  - [x] Open a Pull Request from your fork to the original
  - [x] Add a link to the PR to your _WIP Issue_
- [x] **HTML**
  - [x] Create `index.html` in your `TIY-Assignments` repo 
  - [x] That file should have HTML5 doctype, a head tag, title tag, body tag, and some text.

**Comment by johnmbier** [comment]
https://github.com/johnmbier/johnmbier.github.io/pull/1

**Comment by johnmbier** [comment]
https://github.com/johnmbier/student-roster/commit/4594ba21a1465eb96dc226250102652a8882ffb3

**Comment by bgates** [comment]
The "explain basic classes" was an important part of this assignment.
