### ISSUE TITLE
02 -- Tools on Tuesday -- John Bier

### ISSUE THREAD

**Issue by johnmbier** [TheIronYard--Orlando/2015--SUMMER--ROR#18]
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `ruby-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--Love-Your-Grammar` (cont'd)
    - `TIY-Assignments:02--tools-on-tues`
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `about/methods.md`
    - `ruby-koans`
    - `TIY-Assignments`
      - `car_data.rb`
- [x] **Ruby and Data**
  - [x] Defined Car class
  - [x] Wrote methods on Car
  - [x] Opened mtcar.csv in Ruby
  - [x] Produced output
- [ ] **Reading Ruby**
  - [ ] discussed methods
  - [ ] especially enumerable methods
  - [ ] and defining methods
  - [ ] and classes
    - [ ] and instantiating objects
- [ ] **Ruby Koans**
  - [ ] forked https://github.com/TheIronYard--Orlando/ruby_koans
  - [ ] cloned it locally with `git` or `hub`
  - [ ] worked in branch `02--tools-on-tuesday`
  - [ ] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [ ] opened Pull Request
  - [ ] **NORMAL MODE**
    - [ ] `about_asserts.rb`
    - [ ] `about_asserts.rb`
    - [ ] `about_objects.rb`
    - [ ] `about_arrays.rb`
    - [ ] `about_array_assignment.rb`
    - [ ] `about_hashes.rb`
    - [ ] `about_strings.rb`
    - [ ] `about_iteration.rb`
  - [ ] **BEAST MODE** -- ALL KOANS

**Comment by johnmbier** [comment]
https://github.com/johnmbier/TIY--Assignments/blob/master/car_data.rb

**Comment by bgates** [comment]
What you have isn't bad, but there should be more. At least try to start each section of the hw.

Also, the formatting of your Ruby file should be cleaner. 2 spaces per indentation only. That's a SublimeText issue.
