### ISSUE TITLE
02 -- Tools on Tuesday -- Heidi Roude

### ISSUE THREAD

**Issue by HRoude** [TheIronYard--Orlando/2015--SUMMER--ROR#21]
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `ruby-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--Love-Your-Grammar` (cont'd)
    - `TIY-Assignments:02--tools-on-tues`
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `about/methods.md`
    - `ruby-koans`
    - `TIY-Assignments`
      - `car_data.rb`
- [x] **Ruby and Data**
  - [x] Defined Car class
  - [x] Wrote methods on Car
  - [x] Opened mtcar.csv in Ruby
  - [x] Produced output
- [ ] **Reading Ruby**
  - [ ] discussed methods
  - [ ] especially enumerable methods
  - [ ] and defining methods
  - [ ] and classes
    - [ ] and instantiating objects
- [ ] **Ruby Koans**
  - [ ] forked https://github.com/TheIronYard--Orlando/ruby_koans
  - [ ] cloned it locally with `git` or `hub`
  - [ ] worked in branch `02--tools-on-tuesday`
  - [ ] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [ ] opened Pull Request
  - [ ] **NORMAL MODE**
    - [ ] `about_asserts.rb`
    - [ ] `about_asserts.rb`
    - [ ] `about_objects.rb`
    - [ ] `about_arrays.rb`
    - [ ] `about_array_assignment.rb`
    - [ ] `about_hashes.rb`
    - [ ] `about_strings.rb`
    - [ ] `about_iteration.rb`
  - [ ] **BEAST MODE** -- ALL KOANS

**Comment by HRoude** [comment]
car_strings = IO.readlines("mtcars.csv")

class Car
    attr_reader :name, :gas_mileage, :n_cylinders, 
                :horsepower, :weight, :quarter_mile_time

```
def initialize(name, gas_mileage, n_cylinders,
                horsepower, weight, quarter_mile_time)

    @name = name
    @gas_mileage = gas_mileage
    @n_cylinders = n_cylinders
    @horsepower = horsepower
    @weight = weight
    @quarter_mile_time = quarter_mile_time
end

def land_yacht
     self.weight > 3.5 
end
```

end

cars = car_strings.map do |car_string|
    car_string.gsub!('"','')
    car_array = car_string.split(",")
    car_hash = {    "name" => car_array[0], 
                    "gas_mileage" => car_array[1].to_i, 
                    "n_cylinders" => car_array[2].to_i,
                    "horsepower" => car_array[4].to_i,
                    "weight" => car_array[6].to_i,
                    "quarter_mile_time" => car_array[7].to_i}
end

puts cars.max_by{|car| car["gas_mileage"]}["name"] + " has the best gas mileage."

puts cars.select{|car| car["weight"] > 3.5}.map{|car| car["name"]}
puts "are all the land yachts."

puts cars.select{|car| car["horsepower"] > 200}.map{|car| "the powerful " + car["name"]}

puts cars.select{|car| car["gas_mileage"] > 25}.map{|car| "the fuel efficient " + car["name"]}

puts cars.select{|car| car["weight"] > 3.5}.max_by{|car| car["quarter_mile_time"]}["name"] + " is the quickest of the land yacht."

best_mile_4_cyl =  cars.select{|car| car["n_cylinders"] == 4}.min_by{|car| car["mileage"]}["name"]
best_mile_6_cyl = cars.select{|car| car["n_cylinders"] == 6}.min_by{|car| car["mileage"]}["name"]
best_mile_8_cyl = cars.select{|car| car["n_cylinders"] == 8}.min_by{|car| car["mileage"]}["name"]

cylinder_car_array = [best_mile_4_cyl, best_mile_6_cyl, best_mile_8_cyl]

puts cylinder_car_array

**Comment by bgates** [comment]
The content of car_data.rb is ok, but the location isn't. That should go here: https://github.com/HRoude/TIY-Assignments/blob/02--tools-on-tues/car_data.rb

Your repository is where your code lives. Comments on the issue are for discussing the code (and for setting up a task list, which you did correctly in the first comment.) The issue should also have links to any related PRs (pull requests). The links in the issue are generated automatically when you add a comment in the PR saying it's connected to the issue.
