### ISSUE TITLE
02 -- Tools on Tuesday -- Mark Sadler

### ISSUE THREAD

**Issue by letrado** [TheIronYard--Orlando/2015--SUMMER--ROR#23]
Assignment
- **Yak Shaving**
  - [x] _WIP Issue_: `02 -- Tools on Tuesday -- YOUR NAME`
  - [x] _WIP Branch_:
    - `ruby-koans:02--tools-on-tues`
    - `USERNAME.github.io:01--Love-Your-Grammar` (cont'd)
    - `TIY-Assignments:02--tools-on-tues`
  - [x] _WIP Files_:
    - `USERNAME.github.io`
      - `about/methods.md`
    - `ruby-koans`
    - `TIY-Assignments`
      - `car_data.rb`
- [x] **Ruby and Data**
  - [x] Defined Car class
  - [ ] Wrote methods on Car
  - [x] Opened mtcar.csv in Ruby
  - [x] Produced output
- [x] **Reading Ruby**
  - [x] discussed methods
  - [x] especially enumerable methods
  - [x] and defining methods
  - [x] and classes
    - [ ] and instantiating objects
- [ ] **Ruby Koans**
  - [ ] forked https://github.com/TheIronYard--Orlando/ruby_koans
  - [ ] cloned it locally with `git` or `hub`
  - [ ] worked in branch `02--tools-on-tuesday`
  - [ ] pushed to Github: `git push origin 02--tools-on-tuesday`
  - [ ] opened Pull Request
  - [ ] **NORMAL MODE**
    - [ ] `about_asserts.rb`
    - [ ] `about_asserts.rb`
    - [ ] `about_objects.rb`
    - [ ] `about_arrays.rb`
    - [ ] `about_array_assignment.rb`
    - [ ] `about_hashes.rb`
    - [ ] `about_strings.rb`
    - [ ] `about_iteration.rb`
  - [ ] **BEAST MODE** -- ALL KOANS

**Comment by bgates** [comment]
I'm being a bit lenient with "Excellent!" right now; I know I took the koans off of the requirements for this assignment, but there should really be a link to your pull request for car_data.rb.

**Comment by letrado** [comment]
Trust me, I know nothing I am doing is excellent at this point.

Date: Mon, 25 May 2015 17:30:38 -0700
