### ISSUE TITLE
03 -- Server OOP -- Erik Jenks

### ISSUE THREAD

**Issue by erikjenks** [TheIronYard--Orlando/2015--SUMMER--ROR#25]
- **Yak Shaving**
  - _WIP Issue_: `03 -- Server OOP -- YOUR NAME`
    - [x] link to PR in `USERNAME.github.io`
    - [x] link to PR in `TIY-Assignments`
  -  _WIP Branches_:
    - [X] `USERNAME.github.io:01--love-your-grammar`
    - [x] `TIY-Assignments:03--server-oop`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `about/strings.md`
      - `about/numbers.md`
      - `about/arrays.md`
      - `about/hashes.md`
      - `about/methods.md`
      - `about/enumerable_methods.md`
      - `about/objects.md`
    - `TIY-Assignments`
      - `03--Server-OOP/server.rb`
      - `03--Server-OOP/car_data.csv`
      - `03--Server-OOP/home.html`
      - `03--Server-OOP/template.html.erb`
- **Reading Ruby**
  - [x] Describe Strings
  - [x] Describe Numbers
  - [x] Describe Arrays
  - [x] Describe Hashes
  - [x] Describe Methods
  - [x] Describe Enumerable Methods
  - [x] Describe Objects
- **Your First Server**
  - [x] create TIY-Assignments branch named `03--server-oop`
  - [x] populate the branch with files listed in _WIP BRANCH_
  - [x] opened PR _from_ `03--server-oop` _to_ `master`
  - [x] write a home.html page
  - [x] write a WEBrick server that can serve the home page at `localhost:8000/home`
  - [x] make sure there's a way to stop the server!
  - [x] write a template.html.erb file that could display different selections of cars
  - [x] update your WEBrick server to display multiple car selections
    - [x] compact
    - [x] sporty
    - [x] large
    - [x] Mazda
    - [x] Pontiac
    - [x] luxury (price > $30k)
    - [ ] Are you using the same code repeatedly? Try to eliminate duplication and write each thing once.

**Comment by erikjenks** [comment]
https://github.com/ejenks/TIY-Assignments/pull/4
https://github.com/ejenks/ejenks.github.io/pull/3

**Comment by bgates** [comment]
Love the descriptions of classes in your .github.io!
