### ISSUE TITLE
04--The-Iron-Yelp -- Heidi Roude

### ISSUE THREAD

**Issue by HRoude** [TheIronYard--Orlando/2015--SUMMER--ROR#39]
# The Iron Yelp
- [x] Get data from somewhere
- [x] Parse it into a form Ruby can understand
- [x] Set up a server that interprets an incoming _request_ (like "/action") as a need for some of the data (like 'all the action movies') to be returned in _response_
- [x] Make HTML/ERB templates that can display different collections of data
- [x] All of the following in a folder called `the_iron_yelp`
- [x] which you will add to your `TIY-Assignments` repository
- [x] A `home.html` home page for the site
- [x] A `restaurant.rb` file describing a `Restaurant` class that can be initialized with information about a particular restaurant
- [x] instance methods_ for `Restaurant` 
- [x] You read [Instance vs Class Methods](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/blob/master/Notes/Week1/instance_vs_class_methods.md), right?
- [x] class methods_ on `Restaurant` (ditto) to get collections of restaurant objects
- [x] A `server.rb` file that can use the _class methods_ from `Restaurant` to get collections ready to be displayed on a `restaurants.html.erb` template
- [x] For example, when a person visits the site at `/restaurants`, the server should invoke the class method `Restaurant.all` to get all of the restaurants
- [x] Other ways to group the restaurants include filtering by cuisine (ie `/burgers` or `/vegetarian` etc), sorting by number of reviews or highest average review, cheap places (you define what counts as cheap)
- [x] You should also be able to select a single restaurant at a time, say the most popular one, and display lots of info on it in a `restaurant.html.erb` template
- [x] A `restaurants.html.erb` template to display information on one restaurant at a time
- [x] Also, copy the `restaurants.json` file from this folder and include it in yours
### The Data
- [x]  Get data for another restaurant from the list, add it to `restaurants.json`
- [x] Get it into your `TIY-Assignments` repo, and submit a _pull request_ back to this repo
- [ ] If your pull request can't be merged automatically, fix it.
- [ ] Let me know (with an "at-mention") once your PR can be merged, and I'll merge it.

**Comment by HRoude** [comment]
https://github.com/HRoude/TIY-Assignments/pull/1

**Comment by HRoude** [comment]
the_iron_yelp assignment files in TIY Assignments under Master branch.  I could not get them to save under 04-The_Iron_Yelp the branch from the GitHub desktop app

**Comment by HRoude** [comment]
https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Assignments

For some reason, this is where my assignments ended up.  I still am very lost when it comes to how Github works and where I am suppose to place files.  Sorry!

I cannot get my link for "Best Rated" to function.  Any clues?

**Comment by HRoude** [comment]
https://github.com/HRoude/TIY-Assignments/tree/master/the_iron_yelp

**Comment by bgates** [comment]
For most of your controller methods you made an instance variable called @restaurants_array, which was (most of the time) made by using the #select method, which does indeed return an array. So far, so good. Your "best rated" is the only page in which you populated @restaurants_array using #max_by, which actually returns a single item instead of an array. The fix would be to use a different template, which doesn't expect to deal with an array of restaurants.
