### ISSUE TITLE
05--Acts As Monday--Erik Jenks

### ISSUE THREAD

**Issue by erikjenks** [TheIronYard--Orlando/2015--SUMMER--ROR#50]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Acts As Monday -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `USERNAME.github.io:begin-html-demo`
    - [x] link to PR for `USERNAME.github.io:begin-about-html`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
  - [x] _WIP Branches_:
    - [x] `USERNAME.github.io:journal-week-1`
    - [x] `USERNAME.github.io:begin-html-demo`
    - [x] `USERNAME.github.io:begin-about-html`
    - [x] `TheIronYard--Orlando/student-roster:master`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io`
      - [x] `journal-week-1.md`
      - [x] `about/html.md`
      - [x] `about/html_forms.md`
      - [x] `html_demo/page1.html`
      - [x] `html_demo/page2.html`
    - [x] `TheIronYard--Orlando/student-roster`
      - [x] `2015-05/ROR/`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [x] **HTML Demo**
  - [x] created branch in `USERNAME.github.io` named `begin-html-demo`
  - [x] created new file named `html_demo/page1.html`
    - [x] added a link in that file to `html_demo/page2.html`
  - [x] created new file named `html_demo/page2.html`
  - [x] read up on HTML forms in Mozilla Developer Network website
  - [x] added 'Contact Me' form to `html_demo/page2.html`
- [x] **About HTML**
  - [x] created branch in `USERNAME.github.io` named `begin-about-html`
  - [x] created new file named `about/html.md`
  - [x] created new file named `about/html_forms.md`
- [x] **GitHubbing to Know You, Part 2** (due Thu)
  - [x] merged upstream additions from `TheIronYard/student-roster:master`
  - [x] updated your classmate's Markdown file and opened a PR to merge
  - [x] thumbs up (:+1:) on your PR from your "Special Someone"

**Comment by erikjenks** [comment]
- Journal
  https://github.com/ejenks/ejenks.github.io/pull/4
- Begin-About-HTML
  https://github.com/ejenks/ejenks.github.io/pull/5
- Student-Roster
  https://github.com/TheIronYard--Orlando/student-roster/compare/master...ejenks:patch-1
- Begin-HTML-Demo
  https://github.com/ejenks/ejenks.github.io/pull/6

**Comment by bgates** [comment]
Those journal entries are outstanding. They really let me know exactly where you are. Thanks!
