### ISSUE TITLE
05 - Acts-As_Monday --Mark Sadler

### ISSUE THREAD

**Issue by letrado** [TheIronYard--Orlando/2015--SUMMER--ROR#51]
- [x] **Yak Shaving**
  - _WIP Issue_: `05 -- Acts As Monday -- YOUR NAME`
    - [x] link to PR for `USERNAME.github.io:journal-week-1`
    - [x] link to PR for `USERNAME.github.io:begin-html-demo`
    - [x] link to PR for `USERNAME.github.io:begin-about-html`
    - [x] link to PR for `TheIronYard--Orlando/student-roster:master`
  -  _WIP Branches_:
    - `USERNAME.github.io:journal-week-1`
    - `USERNAME.github.io:begin-html-demo`
    - `USERNAME.github.io:begin-about-html`
    - `TheIronYard--Orlando/student-roster:master`
  - _WIP Files_:
    - `USERNAME.github.io`
      - `journal-week-1.md`
      - `about/html.md`
      - `about/html_forms.md`
      - `html_demo/page1.html`
      - `html_demo/page2.html`
    - `TheIronYard--Orlando/student-roster`
      - `2015-05/ROR/`
- [x] **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
- [ ] **HTML Demo**
  - [x] created branch in `USERNAME.github.io` named `begin-html-demo`
  - [x] created new file named `html_demo/page1.html`
    - [x] added a link in that file to `html_demo/page2.html`
  - [x] created new file named `html_demo/page2.html`
  - [x] read up on HTML forms in Mozilla Developer Network website
  - [ ] added 'Contact Me' form to `html_demo/page2.html`
- [x] **About HTML**
  - [x] created branch in `USERNAME.github.io` named `begin-about-html`
  - [x] created new file named `about/html.md`
  - [x] created new file named `about/html_forms.md`
- [ ] **GitHubbing to Know You, Part 2** (due Thu)
  - [x] merged upstream additions from `TheIronYard/student-roster:master`
  - [x] updated your classmate's Markdown file and opened a PR to merge
  - [ ] thumbs up (:+1:) on your PR from your "Special Someone"

Journal, Week 1

You've just completed your first week at The Iron Yard. You've learned a lot in a very short amount of time. Take some time tonight to review your notes and write them down. Use whatever format helps you get the ideas out: bulleted lists, stream of consciousness, retelling a story. Consider this a draft that you'll revise a few times throughout the week. Put this work in a branch called journal-week-1 in your USERNAME.github.io repo. Don't forget to link to that PR in your WIP Issue! Here are some suggestions for topics:

*Ruby topics you've mastered
*Ruby topics you're struggling with
*GitHub and its shiny buttons
*Personal retrospective
*Things about the class that have surprised you
*HTML Demo

I decided that the index.html in your TIY-Assignments repo is out of place, so I want it moved - to your USERNAME.github.io repo. Specifically,

_make a branch called begin-html-demo in your USERNAME.github.io repo
*make a file called html_demo/page1.html
  *_the content of that file should be your old index.html from your TIY-Assignments repo
    except the body should just have a paragraph tag which says "This is one of the simplest possible             HTML pages", and then has a link to html_demo/page2.html.
note the quote marks aren't necessary in the HTML document
Next switch over to the next task (About HTML) for some reading and reflecting. Once you've finished that task, finish up this one by adding a simple 'Contact Me' form to html_demo/page2.html

About HTML

Tomorrow we're going to talk about HTML forms, but it will help you to have a little background in them first. The Mozilla Developer Network website has pretty good documentation. Better than the Ruby docs you've had to deal with so far, I think. Not perfect, but good. I want you to read a couple of pages on there, and then reflect on what you've learned (ie write it down in your own words).

Read the MDN pages for an introduction to HTML and HTML forms. Then write down what you've learned in the USERNAME.github.io repo. Specifically,

make a branch called begin-about-html in your USERNAME.github.io repo
make a file called about/html.md which discusses HTML in general
make a file called about/html_forms.md which discusses...well, you know.
Once you've finished those, return to the previous task and finish it up.

GitHubbing to Know You, Part 2

This week, you'll be randomly assigned classmates to interrogate and a question to ask. Then, you get to update their Markdown file in the Student Roster and open a PR for the change.
It's like freshman orientation all over again, with more GitHub and less chance of embarrassing alcohol poisoning. For tonight, ask the person in the class whose last name comes after yours (unless you have the last last name, in which case you go back to the front of the alphabet) for (A) their hometown and (B) cat or dog.

**Comment by bgates** [comment]
Really good journal entries, Mark. It's very helpful to me to see in print exactly where you are.
