### ISSUE TITLE
00 -- Here It Comes  --  Heidi Roude

### ISSUE THREAD

**Issue by HRoude** [TheIronYard--Orlando/2015--SUMMER--ROR#6]
Pre-Work Task List

**Comment by HRoude** [comment]
[X] [Create a Github account](https://github.com/signup)
* [X] [Star the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR)
* [X ] *5 min* Read over [the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/wiki)
* [X ] *5 min* [Create a new *WIP Issue*](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/issues/new)
  * [X ] Named `00 -- Here It Comes -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [X ] With this checklist as the description
* [X ] *5 min* [Edit your Github profile](https://github.com/settings/profile) to provide:
    * [X ] A picture, so I can recognize your face.
    * [X ] Your full name, so I can recognize your name.
    * [X ] A valid public email address, so I can contact you if I need to.
* [X ] *10 min* Read the `README.md` files in:
    * [X ] [Assignments](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Assignments)
    * [X ] [Notes](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Notes)
* [X ] *15 min* [Install Homebrew](http://brew.sh) on your Mac
    * [X ] Open `Terminal.app`
    * [X ] [Install Homebrew and the `brew` command](http://brew.sh/#install)
    * [X ] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
* [X ] *10 min* Using the `brew` command, install the following packages:
    * [X ] `zsh`
    * [X ] `git`
    * [X ] `hub`
    * [X ] `chruby`
    * [X ] `ruby-install`
* [X ] *10 min* Using the `ruby-install` command, install Ruby 2.2.2.
* [X ] *5 min* Set the default version of Ruby to 2.2.2.
* [X ] *10 min* Add the output of the following commands as comments on your *WIP Issue*:
  * [X ] `which zsh && zsh --version`
  * [X] `which git && git --version`
  * [X ] `which hub && hub --version`
  * [X ] `which ruby && ruby -v`

**Comment by HRoude** [comment]
- [X] [Create a Github account](https://github.com/signup)
- [X] [Star the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR)
- [X] _5 min_ Read over [the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/wiki)
- [X] _5 min_ [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/issues/new)
  - [X] Named `00 -- Here It Comes -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [X] With this checklist as the description
- [X] _5 min_ [Edit your Github profile](https://github.com/settings/profile) to provide:
  - [X] A picture, so I can recognize your face.
  - [X] Your full name, so I can recognize your name.
  - [X] A valid public email address, so I can contact you if I need to.
- [X] _10 min_ Read the `README.md` files in:
  - [X] [Assignments](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Assignments)
  - [X] [Notes](https://github.com/TheIronYard--Orlando/2015--SUMMER--ROR/tree/master/Notes)
- [X] _15 min_ [Install Homebrew](http://brew.sh) on your Mac
  - [X] Open `Terminal.app`
  - [X] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [X] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
- [X] _10 min_ Using the `brew` command, install the following packages:
  - [X] `zsh`
  - [X] `git`
  - [X] `hub`
  - [X] `chruby`
  - [X] `ruby-install`
- [X] _10 min_ Using the `ruby-install` command, install Ruby 2.2.2.
- [X] _5 min_ Set the default version of Ruby to 2.2.2.
- [X] _10 min_ Add the output of the following commands as comments on your _WIP Issue_:
  - [X] `which zsh && zsh --version`
  - [X] `which git && git --version`
  - [X] `which hub && hub --version`
  - [X] `which ruby && ruby -v`
- [X] _10 min_ [Install Caskroom](http://caskroom.io)
- [X] _5 min_ Using `brew cask`, install the following applications:
  - [X] [Google Chrome](http://google.com/chrome)
  - [X] [Sublime Text](http://sublimetext.com)
  - [X] [Slack](http://www.slack.com)
- NOTE: The above looks like a lot, but those tasks go quickly. The following items require, and deserve, more time. Don't put them off!  
- [X] _10 min_ [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  - [X] Add a link to your new Github repo as a comment in your WIP Issue.
- [X] _20 min_ Complete the CodeSchool short course, [Try Git](https://www.codeschool.com/courses/try-git)
- [X] _10 min_ Create _another_ new repository called `TIY-Assignments`
  - [X] Check the box to create an initial `README.md` file
  - [X] Select the `CC0` -- "Creative Commons" license for your work
  - [ ] Add a link to your `TIY-Assignments` repo as a comment to your WIP Issue
- [ ] _5 min_ [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
  - [ ] Add a link to your `Fork-and-Spoon` repo as a comment on your _WIP Issue_
- [ ] _10 min_ Install Prezto
  - [ ] Find _and fork_ the Prezto project on Github; add a link as a comment on your _WIP Issue_
  - [ ] Use the `hub` command to clone your fork into your home directory as `.zprezto`: `hub clone prezto .zprezto`
- [X] _3 hr_ Read and complete selected exercises for the [Command Line Crash Course](http://cli.learncodethehardway.org/book/). The command line is another name for the terminal. There are about 10 commands you'll use all the time on the command line, and it's helpful to have them memorized so we can use them right away.  
  - [X] Introduction
  - [X] pwd
  - [X] mkdir
  - [X] cd
  - [X] ls
  - [X] rmdir
  - [X] touch
  - [X] cp
  - [X] mv
  - [X] rm
  - [X] Pipes and Redirection
  - [X] Wildcard Matching
  - [X] What's In Your Environment
  - [X] Changing Environment Variables 
- [X] _20 min_ Read the first four pages about growth vs fixed mindsets at http://mindsetonline.com/whatisit/about/index.html. I'll be honest, this sounded hokey to me when I first read it, but watching how people with the two mindsets performed in previous cohorts, I'm sold on the idea. You have much more control over how much you can learn than you might think.
- [X] _5 hr_ Read the book [Learn to Program](https://pine.fm/LearnToProgram/). That's a terrific tutorial if you've never written any code before, or if you've never worked with Ruby before. You can read the original version on the author's website for free, or follow the link he gives to purchase the latest version. For this assignment, the exercises in the book are optional.
  - [X] 0. Getting Started
  - [X] 1. Numbers
  - [X] 2. Letters
  - [X] 3. Variables and Assignment
  - [X] 4. Mixing It Up
  - [X] 5. More About Methods
  - [X] 6. Flow Control
  - [X] 7. Arrays and Iterators
  - [X] 8. Writing Your Own Methods
  - [X] 9. Classes
  - [X] 10. Blocks and Procs
  - [X] 11. Beyond This Tutorial

### Deliverables:
- [X] _WIP Issue_
  - [X] named `00 -- Here It Comes -- YOUR NAME`
  - [X] with description matching **Tasks**
- [X] A Github Profile with:
  - [X] Identifiable picture of yourself
  - [X] Your full name
  - [X] A valid email address
- [X] Comments on your _WIP Issue_ with output from
  - [X] `which zsh && zsh --version`
  - [X] `which git && git --version`
  - [X] `which hub && hub --version`
  - [X] `which ruby && ruby -v`
- [X] Comments on your _WIP Issue_ with links to your repos for
  - [X] `Hello-World`
  - [X] `TIY-Assignments`
  - [X] `Fork-and-Spoon`
  - [X] `prezto`

**Comment by bgates** [comment]
Hi Heidi! It looks like there are some issues around terminology that we'll need to get straightened out. The `repositories` are sort of like folders on GitHub. I see you have those for Hello World and Fork and Spoon. You also have one that is _intended_ to be `TIY-Assignments`, but the actual name you gave that repo is `00----Here-It-Comes----HEIDI-ROUDE`. You also forked a project related to `prezto`, but not prezto itself.

Also `comments on your WIP issue` are the text that appears on this page - your big list of checkboxes is a comment on a WIP issue, and I'm making another comment on your WIP issue. The output for `which git && git --version` etc should appear as comments on your WIP issue, as should the links to your other repos. 

These are minor things which we can get straightened out very quickly on Monday. I look forward to seeing you in the morning!
