### ISSUE TITLE
09--For Rails--John Bier

### ISSUE THREAD

**Issue by johnmbier** [TheIronYard--Orlando/2015--SUMMER--ROR#74]
- **Yak Shaving**
  - _WIP Issue_: `09 -- For Rails -- YOUR NAME`
    - [ ] link to PR in `TIY-Assignments`
  -  _WIP Branch_:
    - [x] `TIY-Assignments:09--for-rails`
  - _WIP Files_:
    - `TIY-Assignments`
      - `09--for-rails/todo_mvc_v2`
- **TodoMVC**
  - [x] create TIY-Assignments branch named `09--for-rails`
  - [x] create a new Rails project in that branch called `todo_mvc_v2`
  - [x] open PR _from_ `09--for-rails` _to_ `master`
  - [ ] plan how the different parts of the weekend assignment can be translated to a Rails project
    - [x] the database
    - [x] the Todo class
      - [x] stop after these two are in place and test in the rails console
    - [x] the template
    - [x] the controller
      - [ ] and the URLs
        - [ ] keep track of all the URLs your app can handle with `rake routes`
    - [x] don't forget the CSS and JS
  - [ ] once you know where things go, put them there
  - [x] make sure it works in the browser
  - [ ] once it works, refactor
    - [ ] layout
    - [ ] view partial
    - [ ] helper method(s?)

**Comment by bgates** [comment]
so long as you understood everything by the end of lecture, and I think you did
