### ISSUE TITLE
11 -- Blog on Rails -- Leslie Brown

### ISSUE THREAD

**Issue by starspace1** [TheIronYard--Orlando/2015--SUMMER--ROR#85]
- **Yak Shaving**
  - _WIP Issue_: `11 -- Blog on Rails -- YOUR NAME`
    - [x] link to PR in `TIY-Assignments`
  -  _WIP Branch_:
    - [x] `TIY-Assignments:11--blog-on-rails`
  - _WIP Files_:
    - `TIY-Assignments`
      - `11--blog-on-rails`
- **The Blog**
  - [x] create TIY-Assignments branch named `11--blog-on-rails`
  - [x] create a new Rails project in that branch called `first_blog`
  - [x] push back to your GitHub account
  - [x] open PR _from_ `11--blog-on-rails` _to_ `master`
  - [x] generate your models and tables
    - [x] set up a relationship between them
      - [x] in db
      - [x] in code
      - [x] stop after these two are in place and test in the rails console
  - *\* Do the following in any order **
  - [x] Set up your routes
  - [x] make all the required templates
    - [x] listing blog posts
    - [x] showing one blog post
    - [x] making a new blog post
  - [x] make controllers
    - [x] for posts
    - [x] for comments
  - [x] make sure it works in the browser
    - [x] display a list of blog posts
    - [x] display a form to enter a new blog post
    - [x] create a new blog post
    - [x] show details of one post
    - [x] make a comment on a post
    - [x] display an edit form for a blog post
    - [x] delete a blog post
    - [x] edit and delete a comment
  - [x] use some css resources to make the app look less bad
## Extras

If you get through all that, there are many different directions you can go. Here are some ideas:
- find a way to generate lots of [lorem ipsum](http://www.lipsum.com/) of one kind or another to make 100 posts
- use a pagination gem to list posts 10 at a time
- promote `author` to be a separate class instead of just a field in both posts and comments
  - make appropriate relationships between authors and posts and comments
  - make it possible to add new authors (and edit/delete/etc)
  - display posts and/or comments by author
- add [tags](http://en.wikipedia.org/wiki/Tag_%28metadata%29) to posts. Each post could have multiple tags, and each tag could have multiple posts. Display a list of tags along with each post

**Comment by bgates** [comment]
The new material looks good. There are 258 files in that PR, because I haven't been having you close old PRs and because you have been branching off of existing branches instead of off of master.
